const ALERT_SHOW_TIME = 3000;
const CURRENT_PIN_SETTINGS = {
  size: [28, 44],
  anchor: [14, 44]
};
const SIMPLE_PIN_SETTINGS = {
  size: [28, 44],
  anchor: [20, 40]
};
const RERENDER_DELAY = 500;
const DEFAULT_MAP_SETTINGS = {
  lat: 66.417,
  lng: 94.25,
  scale: 3
};

const MAP_ADDRESS_SCALE = 12;

export {
  ALERT_SHOW_TIME,
  CURRENT_PIN_SETTINGS,
  SIMPLE_PIN_SETTINGS,
  DEFAULT_MAP_SETTINGS,
  MAP_ADDRESS_SCALE,
  RERENDER_DELAY
};
